name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'     
        required: true
        type: string

jobs:
  release:
    runs-on: macos-latest
    steps:
    
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
          
      - name: Build xcframework
        run: |
          cd apple
          make
          cd target
          zip -ry ClashKit.xcframework.zip ./ClashKit.xcframework
          
      - name: Detect checksum
        run: |
          export TEMP=`shasum -a 256 apple/target/ClashKit.xcframework.zip`
          export CHECKSUM=${TEMP:0:64}
          echo "FILE_CHECKSUM=${CHECKSUM}" >> $GITHUB_ENV
          unset CHECKSUM
          unset TEMP

      - name: Update package file
        run: |
          echo "// swift-tools-version:5.5" > Package.swift
          echo "" >> Package.swift
          echo "import PackageDescription" >> Package.swift
          echo "" >> Package.swift
          echo "let package = Package(" >> Package.swift
          echo "  name: \"ClashKit\"," >> Package.swift
          echo "  products: [" >> Package.swift
          echo "    .library(name: \"ClashKit\", targets: [\"ClashKit\"])" >> Package.swift
          echo "  ]," >> Package.swift
          echo "  targets: [" >> Package.swift
          echo "    .binaryTarget(" >> Package.swift
          echo "      name: \"ClashKit\"," >> Package.swift
          echo "      url: \"https://github.com/AppleClash/ClashKit/releases/download/${{ github.event.inputs.version }}/ClashKit.xcframework.zip\"," >> Package.swift
          echo "      checksum: \"${{ env.FILE_CHECKSUM }}\"" >> Package.swift
          echo "    )" >> Package.swift
          echo "  ]" >> Package.swift
          echo ")" >> Package.swift
          
      - name: Commit
        run: |
          git config --local user.email "github-actions@users.noreply.github.com"
          git config --local user.name "github-actions"
          git config remote.origin.url "https://${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/AppleClash/ClashKit.git"
          git add ./Package.swift
          git commit -m "Release ${{ github.event.inputs.version }}!!!" -a
          git push origin main
          
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          tag_name: ${{ github.event.inputs.version }}
          files: apple/target/ClashKit.xcframework.zip
